"""
Dev playground
"""

from htmldocx import HtmlToDocx
from docx import Document

import sys
sys.path.append(".")


html = """
<title>Sources of Law, Constitutional Issues and Initiation of the Criminal Process</title><br/><p class="hide">[<a href="https://bblearn-blaed.griffith.edu.au/webapps/blackboard/content/listContentEditable.jsp?content_id=_6474207_1&amp;course_id=_95478_1">Original Bb page</a>]</p><br/><h1>Introduction</h1>
<p class="hide">Item headers</p><p class="hide">
-- Enabled: :: Review, Statistics Tracking<br \=""/>
</p>
<p><div class="vtbegenerated">

<p style="text-align: justify;">We begin this course by examining the sources of Canadian criminal law and the constitutional framework in which this body of law is applied. The <em>Canadian Charter of Rights and Freedoms</em> restrains the government's ability to enact and apply criminal laws by recognising various rights, and most <em>Charter </em>litigation arises within the context of criminal cases. We also lay the foundation this week for an understanding of the criminal justice system and the trial process, and we discuss the adversarial nature of criminal proceedings and the sources of police power. </p>
</div></p>
<h1>Topic 1A: Sources of Canadian Criminal Law</h1>
<p class="hide">Item headers</p><p class="hide">
-- Enabled: :: Review, Statistics Tracking<br \=""/>
</p>
<p><div class="vtbegenerated">

<p style="text-align: justify;">There are three main sources of criminal law in Canada, namely i) the Constitution, ii) statutes enacted by the legislatures (including the <em>Criminal Code of Canada</em>), and iii) judge-made common law in the form of defences that have not been codified and common law presumptions of fault. As the "supreme law of the land," the Constitution prevails over both statutes and the common law. This means that criminal laws enacted by Parliament can be struck down if they do not comply with the Constitution. In addition, statutes prevail over the common law, largely due to concerns over clarity and certainty in the law where individuals stand to lose their liberty.</p>
<p style="text-align: justify;">Each of these sources is discussed in this video lecture.</p>
<p style="text-align: justify;">PDF slides for the lecture are avaiable here: 
<span class="canvasFileLink">5251 1A Sources of Law.pdf</span>

<br/> </p>
<p><p class="embed">&lt;iframe allowfullscreen="" height="420" mozallowfullscreen="mozallowfullscreen" src="/webapps/echo-library-BB5bb70f08ac35e/ltiLaunch.jsp?mediaId=ae3557f4-1fb5-40f4-9b8b-09da7a2d7af9&amp;amp;course_id=5251LAW_3218_GC" title="5251LAW_1A_Sources+o-s1-full.mp4" webkitallowfullscreen="webkitallowfullscreen" width="640"&gt;&lt;/iframe&gt;</p> <br/><br/></p>

<h2 style="letter-spacing: normal; font-size: 16.9px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 26.195px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><span style="color: #c02424; text-transform: uppercase;">READ</span> about this topic</h2>
<h3 style="letter-spacing: normal; font-size: 14.95px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.1725px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><span style="color: #c02424; text-transform: uppercase;">OPTIONAL</span></h3>

<h3 style="letter-spacing: normal; font-size: 14.95px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.1725px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><i>Frey v Fedoruk et al</i>, [1950] SCR 517</h3>
<p>This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/2724/index.do" rel="noopener" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; line-height: 20.15px; text-shadow: none; letter-spacing: normal; color: #8c2f2f; text-decoration: underline;" target="_blank">click here to read</a>).</p>


<h3 style="letter-spacing: normal; font-size: 14.95px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.1725px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><i>R v Jobidon</i>, [1991] 2 SCR 714</h3>
<p>This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/784/index.do" rel="noopener" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; line-height: 20.15px; text-shadow: none; letter-spacing: normal; color: #8c2f2f; text-decoration: underline;" target="_blank">click here to read</a>).</p>


<p style="font-family: 'Open Sans', sans-serif; overflow-wrap: break-word; margin-bottom: 1em; color: #111111; font-size: small; text-align: left; background-color: #ffffff; clear: both; text-shadow: none;">
<span style="font-family: 'Open Sans', sans-serif; margin: 0px; padding: 0px; border-width: 0px; outline-width: 0px; font-weight: bold; font-size: 16.9px; color: #c02424; text-transform: uppercase; background-color: #ffffff; float: none; text-shadow: none; display: inline;">EXPLORE</span>
<span style="font-family: inherit; margin: 0px; padding: 0px; border-width: 0px; outline-width: 0px; font-weight: bold; font-style: inherit; font-size: 16.9px; text-shadow: none;"> the Criminal Code of Canada, RSC 1985, c C-46 </span>
</p>
<p style="font-family: 'Open Sans', sans-serif; overflow-wrap: break-word; margin: 0px 0px 1em; font-size: small; text-decoration-line: none; padding: 0px; border-width: 0px; outline-width: 0px; line-height: 20.15px; caret-color: #000000; color: #000000; background-color: #ffffff; text-shadow: none;">
<ul>
<li>Explore broadly, but in particular ss 8 and 9 for this topic</li>
<li><span style="font-size: 10pt;">The statute is available on the Justice<span style="font-family: inherit; margin: 0px; padding: 0px; border-width: 0px; outline-width: 0px; font-style: inherit; text-shadow: none;"> Laws Website <a href="https://laws-lois.justice.gc.ca/eng/acts/C-46/page-4.html#docCont" rel="noopener" target="_blank">here</a></span> </span></li>
</ul>
</p>
</div></p>
<h1>Topic 2A: Constitutional Issues in Criminal Law</h1>
<p class="hide">Item headers</p><p class="hide">
-- Enabled: :: Review, Statistics Tracking<br \=""/>
</p>
<p><div class="vtbegenerated">
<p style="text-align: justify;">Constitutional law is relevant to Canadian criminal law for a number of reasons. First of all, only the federal Parliament can enact laws concerning criminal law and procedure, pursuant to section 91(27) of the <em>Constitution Act, 1867. </em>Key pieces of federal criminal legislation are the Criminal Code of Canada, the <em>Controlled Drugs and Substances Act</em> and the <em>Youth Criminal Justice Act</em>. However, the provinces can also create offences, so long as the dominant purpose of the legislation is to regualte a matter within provincial jurisdiction. The provinces have enacted highway traffic offences, as well as regulatory and public welfare offences, pursuant to their powers under section 92 of the <em>Constitution Act, 1867.</em> In addition, the Constitution plays a critical role in protecting the rights of individuals within the criminal justice system. Police, prosecutors, prison officials, and the courts must ensure that the rights of the accused under the <em>Charter</em> are not violated. Where a violation occurs, remedies are available under section 24 of the <em>Charter</em>. Thus, constitutional law imposes limits upon government actors within the criminal context.</p>
<p>This video provides an introduction to the role of the <em>Charter </em>in Constitutional Law.</p>
<p><p class="embed">&lt;iframe allowfullscreen="" height="420" mozallowfullscreen="mozallowfullscreen" src="/webapps/echo-library-BB5bb70f08ac35e/ltiLaunch.jsp?mediaId=12d33d42-41c7-40ac-9af5-ea545057a944&amp;amp;course_id=5251LAW_3218_GC" title="5251LAW_2A_Consti.mp4" webkitallowfullscreen="webkitallowfullscreen" width="640"&gt;&lt;/iframe&gt;</p> <br/><br/></p>


<h3 style="letter-spacing: normal; font-size: 14.95px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.1725px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><span style="color: #c02424; text-transform: uppercase;">OPTIONAL</span></h3>

<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Malmo-Levine; R v Caine</em>, [2003] 3 SCR 571</span></h3>
<p>This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/2109/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;"></em><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.949999809265137px; line-height: 23.172500610351563px;">R v Labaye,</em> [2005] 3 SCR 728</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/2263/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i>R v Oakes</i>, [1986] 1 SCR 103</span></h3>
<p>This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/117/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank"> click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Starr, </em>[2000] 2 SCR 144</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/1804/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i>R v JHS</i>, [2008] 2 SCR 152</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/4641/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank"> click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i>R v Lifchus</i></span><span style="font-size: 14.95px; font-weight: bold;">, [1997] 3 SCR 320</span></h3>
<p>This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/1543/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;"></em><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.949999809265137px; line-height: 23.172500610351563px;">R v Cinous</em>, [2002] 2 SCR 3</span></h3>
<p>This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/1968/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i>R v Fontaine</i></span><span style="font-size: 14.95px; font-weight: bold;">, [2004] 1 SCR 702</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/2140/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Jordan, </em>[2016] 1 SCR 631</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/16057/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank"> click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em>R v Cody</em>, [2017] 1 SCR 659</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/16693/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>

<p><img height="75" src="https://app.secure.griffith.edu.au/gois/icon-set/icon-reading.png" style="float: left;" width="98"/><span style="font-size: 14.95px; font-weight: bold;"><em>Canada (Attorney General) v Bedford</em>, [2013] 3 SCR 1101 </span></p>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website 
(<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/13389/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank"> click here to read</a>).</p>



<p style="clear: both;"><span style="color: #c02424; font-family: 'Open Sans', sans-serif; font-size: 16.9px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: bold; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: uppercase; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">EXPLORE</span><span style="font-size: 16.9px; font-weight: bold;"> the Constitution Acts, 1867 to 1982</span></p>
<p style="text-shadow: none !important; letter-spacing: normal; margin: 0px 0px 1em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 13px;">Review and familiarise yourself with sections 91(27) and 92(14) of the <em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 13px; line-height: 20.149999618530273px;">Constitution Act, 1867</em> and section 52 of the <em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 13px; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Constitution Act, 1982</em>, as well as sections 7 to 14 of the <em>Canadian Charter of Rights and Freedoms</em>. <br style="text-shadow: none !important; letter-spacing: normal !important; line-height: 20.149999618530273px;"/><br/><br/><br/><br/></span></p>
<div style="overflow: hidden;">
<div style="float: left;">
<img src="https://app.secure.griffith.edu.au/gois/icon-set/icon-webLink.png" style="text-shadow: none !important; letter-spacing: normal !important; border: 0px; cursor: default; margin: 0px; padding: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; vertical-align: middle; line-height: 20.149999618530273px; max-width: 100%; height: auto;"/>
</div>
<div style="overflow: hidden;">
<h4 style="text-shadow: none !important; letter-spacing: normal !important; font-size: 19.5px; margin: 0px 0px 0.7em; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-family: inherit; line-height: 30.225000381469727px;">Government of Canada, Justice Laws Website</h4>
<p style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px 0px 1em; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; line-height: 20.149999618530273px;"><a href="https://laws-lois.justice.gc.ca/eng/Const/" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.149999618530273px;" target="_blank">Click here to view the website</a></p>
</div>
</div>




<h2></h2>


<h3 style="margin-top: -15px;"></h3>
<h3 style="margin-top: -15px;"><span style="color: #c02424; text-transform: uppercase;">Watch [OPTIONAL]</span> Transforming the Criminal Justice System: Court Delays</h3>
<p style="text-align: justify;"><span style="background-color: #ffffff;">This video by the Department of Justice Canada depicts the impact of lengthy court delays on the families of victims of crime. </span></p>
<p><p class="embed">&lt;iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/lm7ELdQ1_qc" width="560"&gt;&lt;/iframe&gt;</p></p>


<h3 style="margin-top: -15px;"><span style="color: #c02424; text-transform: uppercase;">WATCH [OPTIONAL]</span><span class="Apple-converted-space"> </span>SCC addresses issue of unreasonable delay for trials</h3>
<p><p class="embed">&lt;iframe frameborder="0" height="315" src="https://www.youtube.com/embed/OAmhdbTx5Jc" width="560"&gt;&lt;/iframe&gt;</p></p>


</div></p>
<h1>Topic 1B: The Adversarial Process</h1>
<p class="hide">Item headers</p><p class="hide">
-- Enabled: :: Review, Statistics Tracking<br \=""/>
</p>
<p><div class="vtbegenerated">

<p style="text-align: justify;">Criminal liability is determined within an adversarial process, and a trial is the opportunity for the Crown prosecutor to prove the specific allegation made in the charge (information or indictment) beyond a reasonable doubt. Trials occur before a neutral, impartial trier of law (to make legal decisions) and a neutral, impartial trier of fact (i.e. the jury, to make factual findings at the end of the trial), where the offence charged warrants a jury trial. Otherwise, most trials occur before a <span style="caret-color: #000000; color: #000000; font-family: 'Open Sans', sans-serif; font-size: 13px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; display: inline !important; float: none;">neutral, impartial trier of fact (i.e. a judge) who makes determinations on both legal and factual matters. The prosecutor is an advocate on behalf of the Crown, but also a quasi-judicial officer. Defence counsel advocates on behalf of accused, but is also an officer of the court, and thereforemust be respectful and honest with the court and must not attempt to mislead the court as to the state of the law. Key aspects of the adversarial process are discussed in this section. </span></p>

<p style="text-align: justify;"><span style="caret-color: #000000; color: #000000; font-family: 'Open Sans', sans-serif; font-size: 13px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; display: inline !important; float: none;">A video lecture for this topic is available here.</span></p>
<p style="text-align: justify;"><span style="caret-color: #000000; color: #000000; font-family: 'Open Sans', sans-serif; font-size: 13px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; display: inline !important; float: none;"><p class="embed">&lt;iframe allowfullscreen="" height="420" mozallowfullscreen="mozallowfullscreen" src="/webapps/echo-library-BB5bb70f08ac35e/ltiLaunch.jsp?mediaId=ee4f791a-9a88-45e9-bcb4-7ede7c97102f&amp;amp;course_id=5251LAW_3218_GC" title="5251LAW_1B_The+Adverial+process+post.mp4" webkitallowfullscreen="webkitallowfullscreen" width="640"&gt;&lt;/iframe&gt;</p> <br/> <br/><br/></span></p>
<p style="text-align: justify;">PDF slides from the lecture can be viewed here: <span style="caret-color: #000000; color: #000000; font-family: 'Open Sans', sans-serif; font-size: 13px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; display: inline !important; float: none;">
<span class="canvasFileLink">5251 1B Adversarial Process.pdf</span>

<br/> </span></p>


<h2 style="letter-spacing: normal; font-size: 16.9px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 26.195px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><span style="color: #c02424; text-transform: uppercase;">OPTIONAL</span></h2>

<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Gunning</em>, [2005] 1 SCR 627</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/2228/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;"></em><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.949999809265137px; line-height: 23.172500610351563px;">R v Hamilton,</em> [2004] OJ No 3252</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://www.ontariocourts.ca/decisions/2004/august/C39716.pdf" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i style="text-shadow: none !important; letter-spacing: normal !important; line-height: 23.172500610351563px;">Krieger v Law Society of Alberta</i>, [2002] 3 SCR 372</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/2007/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Nixon,<span class="Apple-converted-space"> </span></em>[2011] 2 SCR 566</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/7949/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i style="text-shadow: none !important; letter-spacing: normal !important; line-height: 23.172500610351563px;">R v Babos</i>, [2014] 1 SCR 309</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/13487/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i style="text-shadow: none !important; letter-spacing: normal !important; line-height: 23.172500610351563px;">R v Anderson</i></span><span style="font-size: 14.95px; font-weight: bold;">, [2014] 2 SCR 167</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/14222/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>



<p style="clear: both;"><span style="color: #c02424; font-family: 'Open Sans', sans-serif; font-size: 16.9px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: bold; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: uppercase; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">EXPLORE </span><span style="font-size: 16.9px; font-weight: bold;">the Model Code of Professional Conduct</span></p>
<p style="text-shadow: none !important; letter-spacing: normal; margin: 0px 0px 1em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 13px;">Review and familiarise yourself with sections 3.3 and 5.1 of the <em>Model Code of Professional Conduct</em> issued by the Federation of Law Societies of Canada. <br style="text-shadow: none !important; letter-spacing: normal !important; line-height: 20.149999618530273px;"/><br/><br/><br/><br/><br/><br/><br/></span></p>
<div style="overflow: hidden;">
<div style="float: left;">
<img src="https://app.secure.griffith.edu.au/gois/icon-set/icon-webLink.png" style="text-shadow: none !important; letter-spacing: normal !important; border: 0px; cursor: default; margin: 0px; padding: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; vertical-align: middle; line-height: 20.149999618530273px; max-width: 100%; height: auto;"/>
</div>
<div style="overflow: hidden;">
<h4 style="text-shadow: none !important; letter-spacing: normal !important; font-size: 19.5px; margin: 0px 0px 0.7em; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: inherit; font-family: inherit; line-height: 30.225000381469727px;">Model Code of Professional Conduct </h4>
<p style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px 0px 1em; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; line-height: 20.149999618530273px;"><a href="https://flsc.ca/wp-content/uploads/2014/12/conduct1.pdf" onclick="this.href='/webapps/blackboard/content/contentWrapper.jsp?content_id=_6474221_1&amp;displayName=Linked+File&amp;navItem=content&amp;attachment=true&amp;course_id=_95478_1&amp;tab_group=courses&amp;href=https%3A%2F%2Fflsc.ca%2Fwp-content%2Fuploads%2F2014%2F12%2Fconduct1.pdf';"><span color="#8c2f2f" face="inherit" style="color: #8c2f2f; font-family: inherit;"><span style="font-style: inherit;"><span style="text-decoration: underline;">Click here to view the C</span></span></span>ode</a></p>
</div>
</div>




<h3><span style="color: #c02424; text-transform: uppercase;"><img height="75" src="https://app.secure.griffith.edu.au/gois/icon-set/icon-watch.png" style="float: left;" width="98"/>Watch </span>Criminal Trial Process in Ontario at the Ontario Court of Justice</h3>
<p style="text-align: justify;"><span style="background-color: #ffffff;">In this video, Craig Penny, a criminal defence lawyer, discusses the criminal law process for summary conviction and other trials at the Ontario Court of Justice.<br/></span></p>
<p style="margin-left: 90px;"><p class="embed">&lt;iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/0y1xe2BD5ds" width="560"&gt;&lt;/iframe&gt;</p></p>

</div></p>
<h1>Topic 2B: Police Powers and Arrest, Charging Documents and Bail Hearings</h1>
<p class="hide">Item headers</p><p class="hide">
-- Availability: :: Item is hidden from students.<br \=""/>
-- Enabled: :: Review, Statistics Tracking<br \=""/>
</p>
<p><div class="vtbegenerated">

<p style="text-align: justify;">Police officers are independent of the Crown prosecutor in Canada. This independence is important to permit the prosecutor to act as a quasi-judicial officer, and not get too close to the mindset of an investigator. Still, the police will often seek legal advice from Crown prosecutors, including on the wording of search warrants and the scope of their powers. In the interests of securing liberty, the powers of the police are constrained by law, although they can be derived from statute, common law and by implication from statute and common law. Police powers are also significantly limited by the <em>Charter, </em>which provides for an array of rights for an individual who has been detained.<em> </em>Once an individual is arrested, a charging document is issued, known as an information or indictment  (depending on the offence charged) setting out the charges against the person. The powers of the police in relation to investigation and arrest, as well as the procedure for charging an accused, are discussed in this section. </p>




<h2 style="text-shadow: none !important; letter-spacing: normal; font-size: 16.899999618530273px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 26.19499969482422px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="color: #c02424; text-transform: uppercase;">READ</span><span class="Apple-converted-space" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 16.9px; line-height: 26.195px;"> </span>about this topic</h2>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Grant</em>, [2009] 2 SCR 353</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/7799/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;"></em><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.949999809265137px; line-height: 23.172500610351563px;">R v Suberu,</em> [2009] 2 SCR 460</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/7800/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i style="text-shadow: none !important; letter-spacing: normal !important; line-height: 23.172500610351563px;">R v Aucoin</i>, [2012] 3 SCR 408</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/12743/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Cole,<span class="Apple-converted-space"> </span></em>[2012] 3 SCR 34</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/12615/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i style="text-shadow: none !important; letter-spacing: normal !important; line-height: 23.172500610351563px;">R v Spencer</i>, [2014] 2 SCR 212</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Canada Justice Laws website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/14233/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i style="text-shadow: none !important; letter-spacing: normal !important; line-height: 23.172500610351563px;">R v St Cloud</i></span><span style="font-size: 14.95px; font-weight: bold;">, [2015] 2 SCR 328</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/15358/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;"></em><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.949999809265137px; line-height: 23.172500610351563px;">R v Antic</em>, [2017] 1 SCR 509</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/16649/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><i style="text-shadow: none !important; letter-spacing: normal !important; line-height: 23.172500610351563px;">R v MacDonald</i></span><span style="font-size: 14.95px; font-weight: bold;">, [2014] 1 SCR 37</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/13410/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>


<h3 style="text-shadow: none !important; letter-spacing: normal; font-size: 14.949999809265137px; margin: 1em 0px; padding: 0px; border: 0px; outline: 0px; font-weight: bold; font-style: normal; font-family: 'Open Sans', sans-serif; line-height: 23.172500610351563px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><span style="font-size: 14.95px; font-weight: bold;"><em style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: italic; font-family: inherit; font-size: 14.95px; line-height: 23.1725px;">R v Marakah,<span class="Apple-converted-space"> </span></em>[2017] 2 SCR 608</span></h3>
<p style="letter-spacing: normal; margin: 0px 0px 1em 90px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none !important;">This case is available on the Supreme Court of Canada website (<a href="https://scc-csc.lexum.com/scc-csc/scc-csc/en/item/16896/index.do" rel="noreferrer noopener" style="text-shadow: none !important; letter-spacing: normal !important; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-weight: inherit; font-style: inherit; font-family: inherit; font-size: 13px; color: #8c2f2f !important; text-decoration: underline !important; line-height: 20.15px;" target="_blank">click here to read</a>).</p>




</div></p>
<h1>Workshop Preparation</h1>
<p class="hide">Item headers</p><p class="hide">
-- Enabled: :: Review, Statistics Tracking<br \=""/>
</p>
<p><div class="vtbegenerated">
<h3><span style="font-size: 14pt;">Please review the following exercises in advance of the workshop and come prepared to discuss.  </span></h3>
<h4 style="text-shadow: none !important; letter-spacing: normal; margin: 0px 0px 1em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.149999618530273px; caret-color: #000000; color: #000000; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none;"><strong><span style="font-size: 14pt;">Exercise 1 — Doctors on Trial: The use of the <em>Charter</em> challenge as a defence strategy.  </span></strong></h4>
<div style="overflow: hidden;">
<div style="overflow: hidden;">
<p style="padding-left: 40px;"><span style="font-size: 12pt;">
<span class="canvasFileLink">Charter excercise.docx</span>

</span></p>
<h4 style="letter-spacing: normal; margin: 0px 0px 1em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.15px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><strong><span style="font-size: 14pt;">Exercise 2 — </span></strong><strong style="font-family: 'Open Sans', sans-serif; font-size: small;"><span style="font-size: 14pt;"><em>Charter </em>s 11(b) the right to be tried within a reasonable time</span></strong></h4>
<p id="anonymous_element_36" style="font-family: 'Open Sans', sans-serif; margin: -15px 0px 1em; padding: 0px 0px 0px 40px; border-width: 0px; outline-width: 0px; font-size: 16.38px; color: #111111; text-align: left; background-color: #ffffff; text-shadow: none;"><span style="font-family: inherit; margin: 0px; padding: 0px; border-width: 0px; outline-width: 0px; font-weight: inherit; font-style: inherit; font-size: 16.38px; color: #c02424; text-transform: uppercase; text-shadow: none;"><br><span style="font-size: 12pt;">
<span class="canvasFileLink">Right to be tried in a reasonable time.docx</span>

</span><br/> <br/></br></span></p>
<h4 style="letter-spacing: normal; margin: 0px 0px 1em; padding: 0px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.15px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><strong><span style="font-size: 14pt;">Exercise 3 — Interim detention under <em>Criminal Code </em>s 515</span></strong></h4>
<p style="letter-spacing: normal; margin: 0px 0px 1em; padding: 0px 0px 0px 40px; border: 0px; outline: 0px; font-weight: normal; font-style: normal; font-family: 'Open Sans', sans-serif; font-size: small; line-height: 20.15px; caret-color: #000000; color: #000000; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: #ffffff; text-decoration: none; text-shadow: none;"><strong><span style="font-size: 14pt;"><span style="font-size: 12pt;">
<span class="canvasFileLink">Interim detention.docx</span>

</span><br/> </span></strong></p>
</div>
</div>
</div></p>


"""


fred = """

<h3>To discuss in class</h3><p>Bring to class the three biggest takeaways from the readings.</p><div class="activity"><div class="activityImage">
<img alt="Activity icon" src="https://filebucketdave.s3.amazonaws.com/banner.js/images/icons8-dancing-48.png"/>
</div>
<div class="instructions">
<p>What do they say about the contemporary nature of legal practice? How is legal practice ‘global’?</p>
</div>

"""

# Define the mapping from HTML class to Word style
# Each HTML tag has a dict keyed on HTML class where
# the value is the Word style name

STYLE_MAP = {
    "h1": {
        "canvasFile": 'Canvas File',
        "canvasSubHeader": 'Canvas SubHeader',
        "canvasDiscussion": 'Canvas Discussion',
        "canvasQuiz": 'Canvas Quiz',
        "canvasAssignment": 'Canvas Assignment',
        "canvasExternalTool": 'Canvas External Tool',
        'canvasExternalUrl': 'Canvas External Url',
    },
    "p": {
        "embed": 'Embed',
        "hide": "Hide",
        "canvasFileLink": 'Canvas File Link'
    },
    "span": {
        "embed": 'Embed',
        "hide": "Hide",
        "canvasFileLink": 'Canvas File Link'
    }
}

# Start with a blank Word doc that has the Word styles
# from above defined
document = Document('C:\\Users\\s2986288\\code\\Example.docx')

# create the parser and point to the style map
new_parser = HtmlToDocx()
new_parser.style_map = STYLE_MAP

new_parser.add_html_to_document(html, document)

document.save('dev.docx')
